export enum Services {
    AUTH = 'auth',
    PROFILE = 'profile',
    PETITIONS = 'petitions',
    UPLOAD = 'upload',
    USERS = 'users',
}

export enum Endpoints {
    ASSIGN = 'assign',
    TEMPLATES = 'templates',
    TAGS = 'tags',
    CASES = 'cases',
    DRAFTS = 'drafts',
    SECTIONS = 'sections',
    UNITS = 'units',
    VARIANTS = 'variants',
    LOGIN = 'login',
    LOGIN_PASSWORD = 'login/password',
    REFRESH = 'refresh',
    REGISTER = 'register',
    RESET = 'reset',
    FORGOT = 'forgot',
    ROLES = 'roles',
    USERS = '',
    PROFILE_UPDATE = 'update',
    TEMPLATES_COPY = 'copy',
    BLOCK = 'block',
    RESTORE = 'restore',
    MANAGERS = 'managers',
    SET_MANAGERS = 'set-manager',
    DRAFT_CREATE = 'draft-create',
    DRAFT_SAVE = 'draft-save',
    SET_ACTIVE = 'set-active',
    DUPLICATE = 'duplicate',
    SET_STATUS = 'set-status',
    BLANK = 'blank',
    FILL = 'fill',
    SORT = 'sort',
    SET_PDF_SECTION = 'set-pdf-section',
    KEY_WORDS = 'keywords',
}
